version: '3.8'

services:
  mysql:
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mydatabase
    image: mysql:latest
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=attendanceTracker
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    labels:
      kompose.service.type: LoadBalancer
    networks:
      - jointbridge
    

  flaskapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: foreverrp/flask
    environment:
      - MYSQL_DATABASE=attendanceTracker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mysql
    links:
      - mysql
    ports:
      - "5000:5000"
    restart: on-failure
    labels:
      kompose.service.type: LoadBalancer
    networks:
      - jointbridge

  nodeapi:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: foreverrp/node
    environment:
      - MYSQL_DATABASE=attendanceTracker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mysql
    links:
      - mysql
    ports:
      - "3001:3001"
    restart: on-failure
    labels:
      kompose.service.type: LoadBalancer
    networks:
      - jointbridge


  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: foreverrp/react
    ports:
      - "80:80"
    links:
      - flaskapi
    restart: on-failure
    labels:
      kompose.service.type: LoadBalancer
    networks:
      - jointbridge


networks:
  jointbridge:
    driver : bridge
