apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: client-tcp
      name: client-tcp
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: client
      type: LoadBalancer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: flaskapi-tcp
      name: flaskapi-tcp
    spec:
      ports:
        - name: "5000"
          port: 5000
          targetPort: 5000
      selector:
        io.kompose.service: flaskapi
      type: LoadBalancer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-tcp
      name: mysql-tcp
    spec:
      ports:
        - name: "3306"
          port: 3306
          targetPort: 3306
      selector:
        io.kompose.service: mysql
      type: LoadBalancer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: nodeapi-tcp
      name: nodeapi-tcp
    spec:
      ports:
        - name: "3001"
          port: 3001
          targetPort: 3001
      selector:
        io.kompose.service: nodeapi
      type: LoadBalancer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/jointbridge: "true"
        io.kompose.service: client
      name: client
    spec:
      containers:
        - image: react
          name: client
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: OnFailure
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: null
      name: jointbridge
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  io.kompose.network/jointbridge: "true"
      podSelector:
        matchLabels:
          io.kompose.network/jointbridge: "true"
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/jointbridge: "true"
        io.kompose.service: flaskapi
      name: flaskapi
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: attendanceTracker
            - name: MYSQL_HOST
              value: mydatabase
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
          image: flask
          name: flaskapi
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: OnFailure
    status: {}
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/jointbridge: "true"
        io.kompose.service: mysql
      name: mysql
    spec:
      containers:
        - args:
            - mysqld
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: attendanceTracker
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
          image: mysql:latest
          name: mydatabase
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: OnFailure
    status: {}
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubemanifests.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/jointbridge: "true"
        io.kompose.service: nodeapi
      name: nodeapi
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: attendanceTracker
            - name: MYSQL_HOST
              value: mydatabase
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
          image: node
          name: nodeapi
          ports:
            - containerPort: 3001
          resources: {}
      restartPolicy: OnFailure
    status: {}
kind: List
metadata: {}

