apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata: 
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: foreverrp/reactapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---       
apiVersion: v1
kind: Service
metadata:
  name: react
spec:
  selector:
    app: react
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000